### ISSUE TITLE
Cannot install with pip on OSX 10.11.3

### ISSUE THREAD

**Issue by chrisdembia** [pfultz2/cget#10]
I get the following error:

```
$ pip install cget
Collecting cget
  Could not find a version that satisfies the requirement cget (from versions: )
No matching distribution found for cget
```

**Comment by pfultz2** [comment]
Hmm, I am going to look into this. It looks like it is requiring it self as a requirement.

**Comment by chrisdembia** [comment]
> you should be able to install it using python setup.py install.

Yep, that's what I did.

**Comment by pfultz2** [comment]
Ok, so installing directly from pip should work now.

**Comment by chrisdembia** [comment]
Thanks; this works now.
