### ISSUE TITLE
Support setting CMake variables

### ISSUE THREAD

**Issue by foonathan** [pfultz2/cget#18]
This tool is really awesome, in order to use it for my libraries, I need a way to set CMake variables (especially `CMAKE_BUILD_MODE`).

For example like: `cget install -DVARIABLE`

Your tool don't need to worry about handling different configurations for me, my library does it when installing.

**Comment by pfultz2** [comment]
This is actually already supported, the commands `install`, `init`, and `build` all support a define flag. Also, you can add defines in the `requirements.txt` file as well, like this:

```
foonathan/memory -DCMAKE_BUILD_MODE=release
```

I don't have everything documented on the main page, but you can get help using `--help`:

```
$ cget --help
Usage: cget [OPTIONS] COMMAND [ARGS]...

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  build       Build package
  clean       Clear directory
  init        Initialize install directory
  install     Install packages
  list        List installed packages
  pkg-config  Pkg config
  remove      Remove packages
```

And then you can see the help for the `install` command like this:

```
$ cget install --help
Usage: cget install [OPTIONS] [PKGS]...

  Install packages

Options:
  -p, --prefix TEXT  Set prefix used to install packages
  -v, --verbose      Enable verbose mode
  -U, --update       Update package
  -t, --test         Test package before installing by running ctest or check
                     target
  --test-all         Test all packages including its dependencies before
                     installing by running ctest or check target
  -f, --file TEXT    Install packages listed in the file
  -D, --define TEXT  Extra configuration variables to pass to CMake
  -h, --help         Show this message and exit.
```

What's missing is help for the flags that can be used in the `requirements.txt` file. I hope to document all this soon.

Let me know if you run into anymore issues or have questions,

**Comment by foonathan** [comment]
Oh, okay. That's cool then. :D
