### ISSUE TITLE
Add link_directories to cget.cmake

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [pfultz2/cget#39]
The generated `cget.cmake` file does include a `include_directories(SYSTEM ${CMAKE_PREFIX_PATH}/include)` statement.

However, it would be nice if it included a similar `link_directories(${CMAKE_PREFIX_PATH}/lib)` statement.

Right now, I have to add this in my own `CMakeLists.txt`, so this is not a problem, just a suggestion.

**Comment by pfultz2** [comment]
I have thought about it, but packages, generally, use `find_library` to link a library, which is more robust. However, a lot of header-only libraries just assume the headers are available, so the `include_directories` is necessary.

**Comment by usernameiwantedwasalreadytaken** [comment]
Ok. That makes sense.
