### ISSUE TITLE
Using cget with catch

### ISSUE THREAD

**Issue by larzw** [pfultz2/cget#46]
Hello,

Thanks for the great tool! I've got a quick question.

I see that you have a [recipe for catch](https://github.com/pfultz2/cget-recipes/tree/master/recipes/philsquared/catch) already. But, it looks like this goes through the process of **building** a single header file. Instead, I want to download the already made header file from the release tab [here](https://github.com/philsquared/Catch/releases/download/v2.0.0-develop.4/catch.hpp). However, when I try

```
cget install https://github.com/philsquared/Catch/releases/download/v2.0.0-develop.4/catch.hpp --cmake header
```

I get and error, something like...

```
Downloading ......
Extracting archive ....
Unexpected error: <class 'tarfile.ReadError'>
file could not be opened successfully
...
```

Any help is appreciated!

**Comment by pfultz2** [comment]
It treats files as tarballs which it tries to unpack. Let me look into adding support for a single file. 

In general, I haven't add support for this as it is not as much necessary. Usually, a single header file is created so it can be easily copied into a project, whereas with cget you can install the entire project(which can include additional cmake support).

**Comment by pfultz2** [comment]
This is fixed on master now.

**Comment by larzw** [comment]
thank you!
