### ISSUE TITLE
Support for .ipp with --cmake header

### ISSUE THREAD

**Issue by jonathonl** [pfultz2/cget#54]
How do you feel about adding .ipp to the set of patterns in [cget/cmake/header.cmake](https://github.com/pfultz2/cget/blob/master/cget/cmake/header.cmake)? It's somewhat common for header-only libraries to use this convention.

**Comment by jonathonl** [comment]
I would also suggest adding .tcc file extensions.

**Comment by pfultz2** [comment]
This has been updated on master already.
