### ISSUE TITLE
Allow specifying cmake flags to pass onto the requirements

### ISSUE THREAD

**Issue by chrisdembia** [pfultz2/cget#9]
First of all, awesome idea! It'd be nice if the requirements file allowed specifying cmake flags to pass onto the dependencies, e.g., `-DCMAKE_CXX_FLAGS=...`, etc.

**Comment by pfultz2** [comment]
It should already be possible on the master branch(the pip version may not be that update). So you should be able to write this:

```
jgm/cmark -DCMAKE_CXX_FLAGS=-fopenmp
```

Let me know if that doesn't work for you.

**Comment by chrisdembia** [comment]
Oh neat! I'd try but I'm having trouble using cget at all on OSX. See #11. I also can't use `cget install` b/c:

```
  File "/usr/local/lib/python2.7/site-packages/cget-0.0.5-py2.7.egg/cget/prefix.py", line 120, in remove
    pkg_dir = self.get_package_directory(pkg.to_fname())
AttributeError: 'unicode' object has no attribute 'to_fname'
```

**Comment by pfultz2** [comment]
Are you using a special prefix? Does it work without a prefix?

**Comment by chrisdembia** [comment]
I get the same error whether or not I give a prefix.

**Comment by pfultz2** [comment]
Ok, so I can't reproduce this on the latest. Let me know if it still breaks for you.

**Comment by chrisdembia** [comment]
I still have this issue with the latest commit. I'll open a new issue for it, since this issue was about something else anyway.
